spring.application.name=core
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/setu_core_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-256-bit-secret-key-here-make-it-long-enough-for-hs256
jwt.expiration-ms=86400000

ml.service.base-url=https://ritalin-plant-acetone.ngrok-free.dev
chatbot.service.base-url=https://ritalin-plant-acetone.ngrok-free.dev

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=your-brevo-smtp-login
spring.mail.password=your-brevo-smtp-key
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true